# Site settings
title: Panos Petsagkourakis Personal Page
email: ppetsag@gmail.com
description: > # this means to ignore newlines until "baseurl:"
baseurl: "/personal/" # the subpath of your site, e.g. /blog/
url: "ppetsag" # the base hostname & protocol for your site

twitter_username: 
github_username:

# Build settings
markdown: kramdown
